# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from hashlib import md5


class Ui_Login(object):
    def login(self):
        password = self.lineEdit.text()
        if md5((password).encode('utf-8')).hexdigest() == md5('Master'.encode('utf-8')).hexdigest():
            Login.destroy()
            
        else:
            print("Invalid Pasword")
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.setEnabled(True)
        Login.resize(800, 600)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Login.setWindowIcon(icon)
        Login.setWindowFilePath("")
        self.centralwidget = QtWidgets.QWidget(Login)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 30, 521, 41))
        self.label.setStyleSheet("font: 26pt \"Lucida Calligraphy\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 360, 221, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(140, 90, 581, 41))
        self.label_3.setStyleSheet("font: 8pt \"Kunstler Script\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 130, 271, 231))
        self.label_4.setText("")
        self.label_4.setTextFormat(QtCore.Qt.RichText)
        self.label_4.setPixmap(QtGui.QPixmap("dist/logo.png"))
        self.label_4.setScaledContents(False)
        self.label_4.setObjectName("label_4")
        self.Login_btn = QtWidgets.QPushButton(self.centralwidget)
        self.Login_btn.setGeometry(QtCore.QRect(300, 440, 131, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.Login_btn.setFont(font)
        self.Login_btn.setObjectName("Login_btn")
        self.Login_btn.clicked.connect(self.login)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(300, 360, 301, 31))
        self.lineEdit.setObjectName("lineEdit")
        Login.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Login)
        self.statusbar.setObjectName("statusbar")
        Login.setStatusBar(self.statusbar)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Login"))
        self.label.setText(_translate("Login", "<html><head/><body><p align=\"center\"><span style=\" font-size:24pt; color:#ff0000;\">Created by Ishan Mitra</span></p></body></html>"))
        self.label_2.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:16pt;\">Enter master pasword:</span></p></body></html>"))
        self.label_3.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:36pt;\">Mitra Electronics and Software, Inc</span></p></body></html>"))
        self.Login_btn.setText(_translate("Login", "Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Login = QtWidgets.QMainWindow()
    ui = Ui_Login()
    ui.setupUi(Login)
    Login.show()
    sys.exit(app.exec_())
